### ISSUE TITLE
This Package not support flutter version 3.22.0

### ISSUE THREAD

**Issue by GokulP48** [juliansteenbakker/duration_picker#26]
Launching lib\main.dart on sdk gphone x86 in debug mode...
Running Gradle task 'assembleDebug'...
../../AppData/Local/Pub/Cache/hosted/pub.dev/device_preview-1.1.0/lib/src/views/tool_panel/sections/section.dart:39:40: Error: The getter 'subtitle' isn't defined for the class 'TextTheme'.
 - 'TextTheme' is from 'package:flutter/src/material/text_theme.dart' ('../../flutter/packages/flutter/lib/src/material/text_theme.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'subtitle'.
                style: theme.textTheme.subtitle?.copyWith(
                                       ^^^^^^^^
../../AppData/Local/Pub/Cache/hosted/pub.dev/device_preview-1.1.0/lib/src/views/tool_panel/sections/settings.dart:56:34: Error: The getter 'backgroundColor' isn't defined for the class 'ThemeData'.
 - 'ThemeData' is from 'package:flutter/src/material/theme_data.dart' ('../../flutter/packages/flutter/lib/src/material/theme_data.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'backgroundColor'.
                  color: toolbar.backgroundColor,
                                 ^^^^^^^^^^^^^^^
../../AppData/Local/Pub/Cache/hosted/pub.dev/device_preview-1.1.0/lib/src/views/tool_panel/sections/settings.dart:87:34: Error: The getter 'backgroundColor' isn't defined for the class 'ThemeData'.
 - 'ThemeData' is from 'package:flutter/src/material/theme_data.dart' ('../../flutter/packages/flutter/lib/src/material/theme_data.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'backgroundColor'.
                  color: toolbar.backgroundColor,
                                 ^^^^^^^^^^^^^^^
../../AppData/Local/Pub/Cache/hosted/pub.dev/device_preview-1.1.0/lib/src/views/theme.dart:31:11: Error: No named parameter with the name 'toggleableActiveColor'.
          toggleableActiveColor: accentColor,
          ^^^^^^^^^^^^^^^^^^^^^
../../AppData/Local/Pub/Cache/hosted/pub.dev/device_preview-1.1.0/lib/src/views/theme.dart:54:11: Error: No named parameter with the name 'toggleableActiveColor'.
          toggleableActiveColor: accentColor,
          ^^^^^^^^^^^^^^^^^^^^^
../../AppData/Local/Pub/Cache/hosted/pub.dev/device_preview-1.1.0/lib/src/views/tool_panel/tool_panel.dart:83:34: Error: The getter 'headline6' isn't defined for the class 'TextTheme'.
 - 'TextTheme' is from 'package:flutter/src/material/text_theme.dart' ('../../flutter/packages/flutter/lib/src/material/text_theme.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'headline6'.
          style: theme.textTheme.headline6?.copyWith(
                                 ^^^^^^^^^
../../AppData/Local/Pub/Cache/hosted/pub.dev/device_preview-1.1.0/lib/src/views/tool_panel/sections/subsections/device_model.dart:175:32: Error: The getter 'subtitle2' isn't defined for the class 'TextTheme'.
 - 'TextTheme' is from 'package:flutter/src/material/text_theme.dart' ('../../flutter/packages/flutter/lib/src/material/text_theme.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'subtitle2'.
        style: theme.textTheme.subtitle2?.copyWith(
                               ^^^^^^^^^
../../AppData/Local/Pub/Cache/hosted/pub.dev/duration_picker-1.1.1/lib/duration_picker.dart:132:14: Error: The getter 'headline2' isn't defined for the class 'TextTheme'.
 - 'TextTheme' is from 'package:flutter/src/material/text_theme.dart' ('../../flutter/packages/flutter/lib/src/material/text_theme.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'headline2'.
            .headline2!
             ^^^^^^^^^
../../AppData/Local/Pub/Cache/hosted/pub.dev/duration_picker-1.1.1/lib/duration_picker.dart:147:44: Error: The getter 'bodyText2' isn't defined for the class 'TextTheme'.
 - 'TextTheme' is from 'package:flutter/src/material/text_theme.dart' ('../../flutter/packages/flutter/lib/src/material/text_theme.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'bodyText2'.
        style: Theme.of(context).textTheme.bodyText2,
                                           ^^^^^^^^^
../../AppData/Local/Pub/Cache/hosted/pub.dev/duration_picker-1.1.1/lib/duration_picker.dart:546:29: Error: The getter 'subtitle1' isn't defined for the class 'TextTheme'.
 - 'TextTheme' is from 'package:flutter/src/material/text_theme.dart' ('../../flutter/packages/flutter/lib/src/material/text_theme.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'subtitle1'.
    final style = textTheme.subtitle1;
                            ^^^^^^^^^
../../AppData/Local/Pub/Cache/hosted/pub.dev/duration_picker-1.1.1/lib/duration_picker.dart:606:37: Error: The getter 'backgroundColor' isn't defined for the class 'ThemeData'.
 - 'ThemeData' is from 'package:flutter/src/material/theme_data.dart' ('../../flutter/packages/flutter/lib/src/material/theme_data.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'backgroundColor'.
        backgroundColor = themeData.backgroundColor;
                                    ^^^^^^^^^^^^^^^
Target kernel_snapshot failed: Exception

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command 'C:\Users\gokul.p\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 19s
Error: Gradle task assembleDebug failed with exit code 1

**Comment by redguitars97** [comment]
Hi @GokulP48 ,

I'm facing the same issue.

I modified the library locally to bypass the issue.

I don't know if someone will update the library.

Thanks and best regards,
Mattia.

**Comment by juliansteenbakker** [comment]
Fixed with version v1.2.0. Thanks for raising this issue.

**Comment by GokulP48** [comment]
> Fixed with version v1.2.0. Thanks for raising this issue.

Really appreciated!
